# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ltesha <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/15 21:55:45 by ltesha            #+#    #+#              #
#    Updated: 2019/07/16 22:13:31 by ltesha           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SOURCES = ./src/utils.c ./src/operations.c ./src/calc.c ./src/main.c

all:
	gcc -Wall -Wextra -Werror $(SOURCES) -I ./includes/ -o do-op

clean:
	rm -rf do-op
